Feature/advantages
olgachotii/team-proj-grup18 pull request #15
Opened 2021-07-18 12:19 UTC by ValeriiGenn

2021-07-18 13:03 UTC, olgachotii requested changes

2021-07-18 13:03 UTC, olgachotii commented on src/partials/advantages.html
> +  </div>
секцию желательно заворачивать в div class="container" ему уже заданы общие стили в components/_container

2021-07-18 19:07 UTC, ValeriiGenn commented on src/partials/advantages.html
> +  </div>
загорнуто

2021-07-18 19:10 UTC, ValeriiGenn commented
секція advantages закінчена, у цій редакції не бачив.

2021-07-19 07:23 UTC, olgachotii approved these changes

2021-07-19 07:23 UTC, merged